### ISSUE TITLE
Unable to find version '0.5.2' of package 'Cake' when running build.ps1

### ISSUE THREAD

**Issue by Philo** [cake-build/example#3] opened 2016-02-09 10:18 UTC
![image](https://cloud.githubusercontent.com/assets/432217/12913397/5b55a9a6-cf16-11e5-9980-0d960ca0563e.png)

When following the [getting started](http://cakebuild.net/docs/tutorials/getting-started) guide

**Comment by devlead** [comment] 2016-02-09 10:36
Hi @Philo,

Just cloned and tested the example project myself and unfortunately can't reproduce the error.
![image](https://cloud.githubusercontent.com/assets/1647294/12913612/190bb446-cf20-11e5-80f3-01f3644c1d75.png)

You could try launching with nuget manually with version specified:
`C:\temp\dev\gh\cake-build\example\tools [master]> nuget install Cake -Version 0.5.2 -ExcludeVersion -Verbosity detailed`
To see if that results in same error.

Package is available on NuGet (http://www.nuget.org/packages/Cake/0.5.2) so it should work, could also be an temporarily error with nuget, so just retrying might be an option.

**Comment by patriksvensson** [comment] 2016-02-09 11:14
@Philo Do you have any custom NuGet sources registered where Cake does not exist?

**Comment by gep13** [comment] 2016-02-09 13:41
@Philo we have just updated this repo, thanks to some changes from @devlead.  Can you please try running the example script again, and let us know how you get on.

Sorry, that you had some issues.

**Comment by Philo** [comment] 2016-02-09 14:25
@patriksvensson - Yes I have custom sources, a myget feed, then nuget v3, then a local nuget folder

@gep13 - I have tried again with latest, now I get:

_Unable to find version '0.8.0' of package 'Cake'.
Unable to find version '3.0.1' of package 'NUnit.Console'._

I think I'm noticed the problem.

I have a locally pathed nuget.exe at v3.2.0.10516, my package sources only contain v3 sources.  The version of nuget.exe downloaded by the bootstrapper from `http://www.nuget.org/nuget.exe` is v2.8.60717.93.  Therefore it cant/doesnt read the v3 sources.

Adding the v2 nuget source resolves the problem.

Perhaps you should considered adding a nuget.config file to the tools directory to ensure the package sources are available, this could also then be used for any custom tool feeds associated with a build?

**Comment by gitfool** [comment] 2016-04-09 23:22
Exact same problem here. The bootstrapper failed until I updated my NuGet.config (in C:\Users\Sean\AppData\Roaming\NuGet) to include v2:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" /> <!-- needed to fix failure -->
    <add key="TeamCity" value="http://teamcity/guestAuth/app/nuget/v1/FeedService.svc/" />
  </packageSources>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
  <disabledPackageSources />
</configuration>
```

It definitely would be good to smooth over this issue somehow, so the bootstrapper works the _first time_ for the build machine(s) and other devs I'm trying to convince this is awesome. :blush:

**Comment by gitfool** [comment] 2016-04-10 04:32
This is also fixed by leaving NuGet.config alone and updating the bootstrapper source to use `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`. The Cake example source has drifted from the Cake source, which already uses it. ([cake/build.ps1#L20](https://github.com/cake-build/cake/blob/develop/build.ps1#L20)).

**Comment by gep13** [comment] 2016-04-10 18:59
@Philo @gitfool I have just updated the example repo to use the latest version of the bootstrapper, which is located here:

https://github.com/cake-build/bootstrapper/blob/develop/res/scripts/build.ps1

Please let me know if you continue to run into issues.  For now, I am going to close this issue.

Thanks!

**Closed as completed by gep13** 2016-04-10 18:59 UTC
